baseURL = "https://shmel.xyz/"
languageCode = "en-us"
theme = "blowfish"
title = "5HM3L SECURITY"
enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/shmel-logo.png"

[params.author]
  name = "5HM3L | security"
  email = "5hm3l1337@gmail.com"
  image = "img/shmel-logo.png"
  headline = "This is a group of like-minded people and independent experts working for the benefit of society and aimed at ensuring information security."
  bio = "This is a group of like-minded people and independent experts working for the benefit of society and aimed at ensuring information security. We are in no way tied to specific companies or government organizations. Participants perform audits, penetration testing, advise on information security issues, develop information security strategies, and also help with computer incidents."
  links = [
    { telegram = "https://t.me/shmelovod" },
    { github = "https://github.com/5HM3L" },
  ]

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10