---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shmel-blog
  namespace: shmel-blog
  labels:
    app: shmel-blog
spec:
  replicas: 3
  selector:
    matchLabels:
        app: shmel-blog
  template:
    metadata:
      labels:
        app: shmel-blog
    spec:
      containers:
        - name: shmel-blog
          image: registry.shmel.xyz:8443/dev/shmel-blog:blowfish-theme 
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"         
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shmel-blog-service
  namespace: shmel-blog
spec:
  selector:
    app: shmel-blog
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shmel-blog-ingress
  namespace: shmel-blog
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
#spec:
#  tls:
#    - hosts:
#        - shmel.xyz
      #secretName: danielof-services-wc-secret
spec:
  rules:
    - host: shmel.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shmel-blog-service
                port:
                  number: 80